require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.catppuccin"
--require "user.cmp"
--require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.gitsigns"
--require "user.tabs"
require "user.lualine"
-- require "user.dap"
require "user.keymaps"
require "user.harpoon"
